name: CI Build Log Example

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make build script executable
        run: chmod +x scripts/bash.sh

      - name: Run build and save logs
        run: |
          mkdir -p build
          ./scripts/bash.sh | tee build/build.log
          echo "--- Build Log Content ---"
          cat build/build.log

      - name: Upload build log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build/build.log
